### ISSUE TITLE
fix igprof sql generation

### ISSUE THREAD

**Issue by slava77** [cms-cmpwg/profiling#7]
It looks like a large fraction of igprof sql reports fail generation like in 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/igprof/CMSSW_12_2_X_2021-11-26-1100/slc7_amd64_gcc900/profiling/11834.21/MEMsql_step3.10.log

https://twiki.cern.ch/twiki/bin/viewauth/CMS/RecoIntegration#Run_profiler_igprof
was updated some time ago to use a more reliable parsing of the `igprof-analyse` outputs

e.g. -mp analysis
```
igprof-analyse --sqlite -v --demangle --gdb -r MEM_LIVE IgProf.1.gz > ig.1.txt
wget https://raw.githubusercontent.com/cms-sw/cms-bot/master/fix-igprof-sql.py 
python fix-igprof-sql.py ig.1.txt | sqlite3 ig.1.sql3
```

@gartung 

@jpata please take a note, in case looking at IB profiles

**Comment by gartung** [comment]
This sed command is supposed to handle this
https://github.com/cms-cmpwg/profiling/blob/ea6a1fcbf2466403212c39cb88051a882f7bc749/Gen_tool/Gen.sh#L120
but I will update the script to use the python script instead.

**Comment by gartung** [comment]
Fixed in this commit
https://github.com/cms-cmpwg/profiling/commit/ab90f8a5194f07a87e9ae8dfdcdabf9cbd9e3b9c
